### ISSUE TITLE
HUD for deactivated things

### ISSUE THREAD

**Issue by beckyh2112** [EnviroMine/EnviroMine-1.7#130]
I've got four HUD bars on my screen (temp, sanity, air quality, and hydration), but I disabled both air quality and hydration in my config. Using EnviroMine 1.3.114 with the default profile (that being the one I altered to suit my needs). Previously in 113 with both of them disabled, I didn't have the HUD bars air quality and hydration.

**Comment by GenDeathrow** [comment]
Thanks for bringing that to my attention.. Not sure what happened. It was good before I merged into the master file. Ill try to get it fixed soon.

**Comment by GenDeathrow** [comment]
Just Push Out a Hot fix for this.. Its temp till I rewrite some of the code.. but it will work.

**Comment by beckyh2112** [comment]
Thanks for going to the trouble to do that. <3

**Comment by EmpireElement** [comment]
this is also still happening on servers(but wierdly only if you have not played in single player before....)
looking forward to your rewrite :+1:

**Comment by GenDeathrow** [comment]
I have the final fix hopefully coming tonight. I have had a super busy last week or two and dust have time to push these fixes out. But her I am now. I have servers and clients syncing now.  Got some one doing some testing. If I don't get it today look for it tomorrow.

**Comment by GenDeathrow** [comment]
Update posted
